accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from accounts.views import (
    MyLoginView,
    MyLogoutView, 
    CheckUsername, 
    CheckEmail, 
    MyRegisterView,
    PasswordResetRequest,
    ProfileView,
    ProfileEdit,
    RegisterSuccess,
)


app_name = "accounts"
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', MyLoginView.as_view(), name="login"),
    path('logout/', MyLogoutView.as_view(), name="logout"),
    path('register-success/', RegisterSuccess.as_view(), name="register_success"),
    path('register/', MyRegisterView.as_view(), name='register'),
    path('password-change/', PasswordChangeView.as_view(template_name="accounts/password_change.html"), name='password_change'),
    path('password-change-done/', PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name='password_change_done'),
    path('password-reset/', PasswordResetRequest.as_view(), name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html",success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),name='password_reset_complete'),
]

htmx_urlpatterns = [
    path('check-username/', CheckUsername.as_view(), name="check_username"),
    path('check-email/', CheckEmail.as_view(), name='check_email'),
    path('edit-profile', ProfileEdit.as_view(), name='edit_profile'),
]

urlpatterns += htmx_urlpatterns

carts/urls.py
from django.urls import path
from carts.views import (
    CheckboxCheck,
    CartView,
    AddToCart,
    CartItemDelete,
    DeleteOrder,
    RecentOrder,
    ListOfOrders,
    DetailOrder,
)



app_name="carts"
urlpatterns = [

    path('', CartView.as_view(), name="cart"),
    path('add-to-cart/<int:pk>/', AddToCart.as_view(), name="add_to_cart"),
    path('checkout/', CheckboxCheck.as_view(), name="checkout"),
    path('recent-order/', RecentOrder.as_view(), name="recent_order"),
    path('orders/', ListOfOrders.as_view(), name='orders'),
    path('order-detail/<int:pk>/', DetailOrder.as_view(), name="detail_order")
]

htmx_urlpatterns = [
    path('cart-item-delete/<int:pk>/', CartItemDelete.as_view(), name="cart_item_delete"),
    path('delete-order/<int:pk>/', DeleteOrder.as_view(), name="delete_order")
]

urlpatterns += htmx_urlpatterns

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "BOOKSITE Admin"
admin.site.site_title = "BOOKSITE Admin Portal"
admin.site.index_title = "Welcome to BOOKSITE Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mybooksite.urls")),
    path('accounts/', include("accounts.urls")),
    path('carts/', include("carts.urls")),
    # path('accounts/', include("django.contrib.auth.urls")),
] 

accounts/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User



gender_choice = (
        ("Male","Male"),
        ("Female", "Female"),
        ("Other", "Other"),
    )

class Profile(models.Model):

    
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.ImageField(upload_to="avatar/", null=True, blank=True)
    address = models.CharField(max_length=100, null=True)
    cellphone_number = models.PositiveIntegerField(null=True)
    gender = models.CharField(max_length=6, choices=gender_choice, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.user.username

accounts/forms.py
from pyexpat import model
from attr import attr, fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, gender_choice
from datetime import datetime





class ProfileForm(forms.ModelForm):


    first_name = forms.CharField(label="first", required=True, max_length=50)
    last_name = forms.CharField(required=True, max_length=50)
    email = forms.EmailField(required=True)
    address = forms.CharField(required=True)
    gender = forms.ChoiceField(required=True, choices=gender_choice,
                               widget=forms.RadioSelect,
                               )
    cellphone_number = forms.IntegerField(required=True)

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'address',
            'cellphone_number',
            'gender',
            'avatar',
        ]

    
class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True, min_length=4, max_length=10)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
            
        return user

accounts/views.py
import re
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth import logout, login
from django.contrib.auth import get_user_model
from django.urls import reverse
from accounts.forms import RegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q 
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from carts.views import get_count_cart
from .forms import ProfileForm
from .models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View



class MyLoginView(View):
    template = 'accounts/login.html'
    
    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
        context = {
            'form': form,
            'count': 0
        }
        return render(request, self.template, context)


    
    def get(self, request):
        form = AuthenticationForm(request)
        if request.user.is_authenticated:
            return redirect('/')
        context = {
            'form': form,
            'count': 0
        }

        return render(request, self.template, context)



class MyLogoutView(View):
    
    def get(self, request):
        logout(request)

        return redirect('mybooksite:index')



class CheckUsername(View):

    def post(self, request):
        username = request.POST.get('username')
        if username:
            if len(username) < 4:
                context = {
                    'msg': 'Username must have atleast 4 characters',
                    'color': 'text-red-700',
                }

                return render(request, "accounts/partials/invalid_username.html", context)
            if get_user_model().objects.filter(username=username).exists():
                context = {
                    'msg': 'Username is already exists',
                    'color': 'text-red-700',
                    }

                return render(request, "accounts/partials/invalid_username.html", context)
            else:
                context = {
                    'msg': 'Username is available',
                    'color': 'text-green-600',
                     }

                return render(request, "accounts/partials/invalid_username.html", context)
        else:
            context = {
                'msg': 'This field is required',
                'color': 'text-red-700',
                }
            return render(request, "accounts/partials/invalid_username.html", context)

    def get(self, request):
        return redirect('accounts:register')
        


class CheckEmail(View):
    regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    def post(self, request):
        email = request.POST.get('email')
        if email:
            if re.search(self.regex, email):
                return render(request, "accounts/partials/valid_email.html")
            else:
                return render(request,"accounts/partials/invalid_email.html")
        else:          
            return render(request, "accounts/partials/invalid_email_field_required.html")
    
    def get(self, request):
        return redirect('accounts:register')



class MyRegisterView(View):
    template = "accounts/register.html"

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:register_success')
        
        context = {
            'form': form,
            'count':0
        }
        return render(request, self.template, context)

    def get(self, request):
        form = RegisterForm()
        if request.user.is_authenticated:
            return redirect('mybooksite:index')

        context = {
            'form': form,
            'count':0
        }
        return render(request, self.template, context)



class PasswordResetRequest(View):

    def post(self, request):
        password_form = PasswordResetForm(request.POST)
        if password_form.is_valid():
            data = password_form.cleaned_data['email']
            user_email = User.objects.filter(Q(email=data))
            if user_email.exists():
                for user in user_email:
                    subject = 'Password Request'
                    email_template_name = 'accounts/password_message.txt'
                    parameters = {
                        'email': user_email,
                        'domain': 'booksite-demo.herokuapp.com',
                        'site_name': 'mybooksite',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, parameters)
                    try:
                        send_mail(subject, email, '', [user.email], fail_silently=False)
                    except:
                        return HttpResponse("Invalid Header")
                    return redirect('accounts:password_reset_done')
        context = {
            'password_form': password_form
        }
        return render(request, 'accounts/password_reset.html', context)

    def get(self, request):
        password_form = PasswordResetForm()
        context = {
            'password_form': password_form
        }
        return render(request, 'accounts/password_reset.html', context)



class ProfileView(LoginRequiredMixin, View):
    template = 'profile.html'
    
    def get(self, request):
        count = get_count_cart(request)

        context = {
            'count': count
        }

        return render(request, self.template, context)



class ProfileEdit(View):
    template = "accounts/partials/edit_profile.html"
    template_full = "accounts/edit_profile_full.html"

    def post(self, request):
        instance = Profile.objects.get(user=request.user)

        form = ProfileForm(request.POST, request.FILES, instance=instance)

        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            instance.user.first_name = first_name
            instance.user.last_name = last_name
            instance.user.email = email
            instance.user.save()
            form.save()
            return HttpResponseRedirect(reverse('accounts:profile'))
        count = get_count_cart(request)
        context = {
            'form': form,
            'count': count
            }
        return render(request, self.template_full, context)

    def get(self, request):
        form = ProfileForm()
        count = get_count_cart(request)

        if request.htmx:
            return render(request, self.template, { 'form': form })
        return render(request, self.template_full, { 'form': form, 'count': count })



class RegisterSuccess(View):
    template = 'register_success.html'

    def get(self, request):
        if request.user.is_authenticated:
            HttpResponseRedirect(reverse('mybooksite:index'))
        return render(request, self.template)





    

templates/accounts/edit_profile_full.html
{% extends 'base.html' %}

{% block content %}

  <div class="container max-w-[80%]">

    <h2 class="mt-12 mb-5 text-2xl font-semibold text-gray-800">

      My Profile
      
    </h2>

    <div class="max-w-md p-3 mx-auto border border-gray-400 rounded shadow-md">

      <form class="space-y-4" method="post" action="{% url 'accounts:edit_profile' %}" enctype="multipart/form-data">
            
        {% csrf_token %}

        {% if form.errors %}

          <div class="text-xs text-red-700">

            {{form.non_field_errors}}

          </div>
            
        {% endif %}
        
        <div>

          <label class="mb-1 text-gray-800" for="id_first_name">

            First name
            
          </label>

          {% if form.errors %}

            <div class="text-xs text-red-700">

              {{form.errors.first_name}}

            </div>
            
          {% endif %}

          <input class="block w-full mt-2 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600" 
                 type="text" 
                 name="first_name" 
                 maxlength="50" 
                 required="" 
                 id="id_first_name"
                 placeholder="{{request.user.first_name}}"
          >

        </div>

        <div>

          <label class="mb-1 text-gray-800" for="id_last_name">

            Last name

          </label>

          {% if form.errors %}

            <div class="text-xs text-red-700">

              {{form.errors.last_name}}

            </div>
            
          {% endif %}

          <input class="block w-full mt-2 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600" 
                 type="text" 
                 name="last_name" 
                 maxlength="50" 
                 required="" 
                 id="id_last_name"
                 placeholder="{{request.user.last_name}}"
          >

        </div>

        <div>

          <label class="mb-1 text-gray-800" for="id_email">
            
            Email
          
          </label>

          <div class="text-xs text-red-700">

            {{form.errors.email}}

          </div>

          <input class="block w-full mt-2 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
                 type="email" 
                 name="email" 
                 required="" 
                 id="id_email"
                 placeholder="{{request.user.email}}"
          >

        </div>

        <div>

          <label class="mb-1 text-gray-800" for="id_address">
            
            Address
          
          </label>

          <div class="text-xs text-red-700">

            {{form.errors.address}}

          </div>

        <input class="block w-full mt-2 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600" 
               type="text" 
               name="address" 
               required="" 
               maxlength="100" 
               id="id_address"
               placeholder="{{request.user.profile.address}}"
        >

        </div>
      
        <div>

          <label class="mb-1 text-gray-800" for="id_cellphone_number">
            
            Cellphone number
          
          </label>

          <div class="text-xs text-red-700">

            {{form.errors.cellphone_number}}

          </div>

          <input class="block w-full mt-2 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600" 
                 required="" 
                 type="number" 
                 name="cellphone_number" 
                 min="0" 
                 id="id_cellphone_number"
                 placeholder="{{request.user.profile.cellphone_number}}"
          >

        </div>

        <div>
          
          <label class="mb-1 text-gray-800" for="id_gender_0">
            
            Gender
          
          </label>

          <div class="text-xs text-red-700">

            {{form.errors.gender}}

          </div>

          <ul id="id_gender" class="flex items-center mt-2 space-x-2">

            <li>
              
              <label class="text-gray-800" for="id_gender_0">
                
                <input class="text-purple-600 focus:ring-purple-600" type="radio" name="gender" value="Male" required="" id="id_gender_0">

                Male
                
              </label>

            </li>
            
            <li>

              <label class="text-gray-800" for="id_gender_1">

                <input class="text-purple-600 focus:ring-purple-600" type="radio" name="gender" value="Female" required="" id="id_gender_1">

                Female

              </label>

            </li>

            <li>

              <label class="text-gray-800" for="id_gender_2">

                <input class="text-purple-600 focus:ring-purple-600" type="radio" name="gender" value="Other" required="" id="id_gender_2">

                Other

              </label>

            </li>

          </ul>

        </div>
      
        <div>

          <label class="mb-1 text-gray-800" for="id_avatar">

            Avatar

          </label>

          <div class="text-xs text-red-700">

            {{form.errors.avatar}}

          </div>

          <input class="mt-2 text-gray-800" type="file" name="avatar" accept="image/*" id="id_avatar">

        </div>

        <div>
          
          <button type="submit" class="px-3 py-2 text-white bg-purple-600 rounded hover:bg-purple-700">
            
            Submit
          
          </button>

        </div>
    
      </form>
        
    </div>

  </div>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container max-w-[80%] my-10">

  <div id="loginForm" class="max-w-md mx-auto overflow-hidden text-gray-800 bg-white rounded-lg shadow-md">

    <div class="py-5 ml-6 text-2xl font-semibold">

      <h2>Sign in</h2>

    </div>

    {% if form.non_field_errors %}

    <div class="max-w-sm px-6 -mt-3 text-xs text-red-700">{{form.non_field_errors}}</div>
    
    {% endif %}
    <form action="{% url 'accounts:login' %}" method="post">
      {% csrf_token %}
      <div class="flex items-center py-3 ml-6">
        <label class="block" for="text">Username</label>
      </div>
      {% if form.errors.username %}
      <div class="mb-1 ml-6 -mt-3 text-xs text-red-700">
        {{form.errors.username}}
      </div>
      {% endif %}
      <div class="flex items-center justify-center">
        <input
          class="w-full mx-6 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
          type="text"
          name="username"
          placeholder="username"
        />
      </div>
      <div class="py-3 ml-6">
        <label class="block" for="text">Password</label>
      </div>
      {% if form.errors.password %}
      <div class="mb-1 ml-6 -mt-3 text-xs text-red-700">
        {{form.errors.password}}
      </div>
      {% endif %}
      <div class="flex items-center justify-center">
        <input
          class="w-full mx-6 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
          type="password"
          placeholder="Password"
          name="password"
          autocomplete="off"
        />
      </div>

      <div class="flex items-center justify-end py-3 mr-6">
        <a class="text-xs text-purple-600 hover:text-purple-700" href="{% url 'accounts:password_reset' %}"
          >Forgot password?</a
        >
      </div>

      <div class="flex items-center justify-center py-3 mx-6">
        <button type="submit" class="w-full p-2 font-medium text-white bg-purple-600 rounded-lg hover:bg-purple-700">
          Login
        </button>
      </div>
    </form>

    <div class="flex items-center justify-center py-3 text-xs">
      <p class="">
        Don't have an accout?
        <a
          id="registerBtn"
          class="text-purple-600 hover:text-purple-700"
          href="{% url 'accounts:register' %}"
          >Register here</a
        >
      </p>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/password_change.html
{% extends 'base.html' %}

{% block content %}

  <div>

    <h1>Password change</h1>

    <p>
      Please enter your old password, for security's sake, and then enter your new
      password twice so we can verify you typed it in correctly.
    </p>

    <form action="">
      {{form}}
    </form>
    
  </div>
  
{% endblock %}

templates/accounts/password_change_done.html
<div>
  <h1>Password change successful</h1>
  <p>Your password was changed.</p>
</div>

templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block content %}

<div class="container w-[80%] mt-10 text-gray-800">

  <h3 class="mb-3 text-xl">Password Reset</h3>

  <p>
    Forgotten your password? Enter your email address below, and we'll email
    instructions for setting a new one.
  </p>

  <div>
    
    <form class="max-w-md px-2 py-3 mx-auto my-5 rounded-md shadow-md" method="post">
      
      {% csrf_token %}
      
      <label class="" for="id_email">

        Email

      </label>
      
      <input class="w-full mt-1 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
             type="email" 
             name="email" 
             autocomplete="email" 
             maxlength="254" 
             required="" 
             id="id_email"
      >

      <button type="submit" 
              class="px-3 py-2 mt-5 text-white bg-purple-600 rounded-md hover:bg-purple-700"
      >
              
        Submit
      
      </button>
    
    </form>

  </div>
  
</div>
{% endblock content %}

templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<div class="container max-w-[80%] text-gray-800">

  <h2 class="mt-10 text-xl">
    Password reset complete
  </h2>

  <p class="block mt-5">
    Your password has been set. You may go ahead and log
    in now.
  </p>

  <a class="block mt-5 text-purple-600 underline" href="{% url 'accounts:login' %}">Log in</a>
  
</div>

{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %} 

{% block content %}
<div class="max-w-[80%] container">

  <h2 class="mt-5 text-xl text-gray-800">
    Confirm Password Reset
  </h2>

  <div class="flex p-2 mt-10 text-gray-700 border border-purple-300 rounded-sm shadow-md">

    <svg xmlns="http://www.w3.org/2000/svg" 
         class="hidden w-12 h-12 md:block" 
         fill="none" 
         viewBox="0 0 24 24" 
         stroke="currentColor"
    >
      <path stroke-linecap="round" 
            stroke-linejoin="round" 
            stroke-width="2" 
            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
      />
      
    </svg>
    
    <ul class="ml-5 list-disc">
      <li>Your password can't be too similar to your other personal information.</li>
      <li>Your password must contain at least 8 characters.</li>
      <li>Your password can't be a commonly used password.</li>
      <li>Your password can't be entirely numeric.</li>
    </ul>
   
  </div>
  
  <form class="max-w-md px-2 py-3 mx-auto mt-5 rounded-md shadow-md" method="post">

    {% csrf_token %}
    
    {% if form.errors %}
    <div class="mb-2 text-xs text-red-600">
      <p>{{form.new_password2.errors}}</p>
    </div>
    {% endif %}
    

    <div>
      <label for="id_new_password1">New password</label>
      <input class="w-full mt-1 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
            type="password" 
            name="new_password1" 
            autocomplete="new-password" 
            required="" 
            id="id_new_password1"
      >
    </div>
           
    <div class="mt-2">
      <label for="id_new_password2">New password confirmation</label>
      <input class="w-full mt-1 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
            type="password"
            name="new_password2"
            autocomplete="new-password"
            required="" 
            id="id_new_password2"
      >
    </div>

    <button type="submit" 
            class="px-3 py-2 mt-5 text-white bg-purple-600 rounded-md hover:bg-purple-700"
    >
    
      Submit

    </button>
    
  </form>

</div>

 
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content%}

<div class="max-w-[80%] container text-gray-800">

  <h2 class="mt-5 text-xl">
    Password reset sent 
  </h2>

  <p class="mt-10">
    We've emailed you instructions for setting your password, <br>
    if an account exists with the email you entered. <br> You should receive them
    shortly. <br> If you don't receive an email, <br> please make sure you've entered the
    address you registered with, and check your spam folder.
  </p>

</div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{%block content%}
<div class="container max-w-[80%] my-10">
  <div id="registerForm" class="max-w-md mx-auto text-gray-800 bg-white rounded-md shadow-md">
    <div class="py-5 ml-6 text-2xl font-semibold">
      <h2>Create Account</h2>
    </div>
    <form action="{% url 'accounts:register' %}" method="post">
      {% csrf_token %}
      <div class="flex items-center ml-6">
        <label class="block " for="text">Username</label>
      </div>
      {% if form.username.errors %}
      <div id="username-error" class="pb-2 mx-6 mt-2 text-xs text-red-700">
        {{form.username.errors}}
      </div>
      {% else %}
      <div id="username-error" class="pb-2 mx-6 mt-2 text-xs text-green-600"></div>
      {% endif %}
      <div class="flex items-center justify-center">
        <input
          class="w-full mx-6 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
          type="text"
          placeholder="Username"
          name="username"
          hx-post="{% url 'accounts:check_username' %}"
          hx-trigger="keyup changed delay:500ms"
          hx-target="#username-error"
          hx-swap="outerHTML"
        />
      </div>
      <div class="flex items-center mt-3 ml-6">
        <label class="block " for="text">Email Address</label>
      </div>
      {% if form.email.errors %}
      <div id="invalid-email" class="pb-2 mx-6 mt-2 text-xs text-red-700">
        {{form.email.errors}}
      </div>
      {% else %}
      <div id="invalid-email" class="pb-2 mx-6 mt-2 text-xs text-green-600">
      </div>
      {% endif %}
      <div class="flex items-center justify-center">
        <input
          class="w-full mx-6 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
          type="text"
          placeholder="Email Address"
          name="email"
          hx-post="{% url 'accounts:check_email' %}"
          hx-trigger="keyup changed delay:500ms"
          hx-target="#invalid-email"
          hx-swap="outerHTML"
        />
      </div>
      <div class="flex items-center mt-3 ml-6">
        <label class="block " for="text">Password</label>
      </div>
      {% if form.password1.errors %}
      <div class="pb-2 mx-6 mt-2 text-xs text-red-700">
        {{form.password1.errors}}
      </div>
      {% else %}
      <div class="pb-2 mx-6 mt-2 text-xs"></div>
      {% endif %}
      <div class="flex items-center justify-center">
        <input
          class="w-full mx-6 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
          type="password"
          placeholder="Password"
          name="password1"
        />
      </div>
      <div class="mt-3 ml-6">
        <label class="block " for="text">Retype Password</label>
      </div>
      {% if form.password2.errors %}
      <div class="pb-2 mx-6 mt-2 text-xs text-red-700">
        {{form.password2.errors}}
      </div>
      {% else %}
      <div class="pb-2 mx-6 mt-2 text-xs"></div>
      {% endif %}
      <div class="flex items-center justify-center">
        <input
          class="w-full mx-6 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600"
          type="password"
          placeholder="Retype Password"
          name="password2"
        />
      </div>

      <div class="flex items-center justify-center mx-6 mt-5">
        <button type="submit" class="w-full p-2 font-medium text-white bg-purple-600 rounded-lg hover:bg-purple-700">
          Register
        </button>
      </div>
    </form>

    <div class="flex items-center justify-center py-3 text-xs">
      <p class="">
        Already have an account?
        <a id="signBtn" class="text-purple-600 hover:text-purple-700" href="{% url 'accounts:login' %}"
          >Sign In</a
        >
      </p>
    </div>
  </div>
</div>
{%endblock%}