carts/urls.py
from django.urls import path
from carts.views import (
    CheckboxCheck,
    CartView,
    AddToCart,
    CartItemDelete,
    DeleteOrder,
    RecentOrder,
    ListOfOrders,
    DetailOrder,
)



app_name="carts"
urlpatterns = [

    path('', CartView.as_view(), name="cart"),
    path('add-to-cart/<int:pk>/', AddToCart.as_view(), name="add_to_cart"),
    path('checkout/', CheckboxCheck.as_view(), name="checkout"),
    path('recent-order/', RecentOrder.as_view(), name="recent_order"),
    path('orders/', ListOfOrders.as_view(), name='orders'),
    path('order-detail/<int:pk>/', DetailOrder.as_view(), name="detail_order")
]

htmx_urlpatterns = [
    path('cart-item-delete/<int:pk>/', CartItemDelete.as_view(), name="cart_item_delete"),
    path('delete-order/<int:pk>/', DeleteOrder.as_view(), name="delete_order")
]

urlpatterns += htmx_urlpatterns

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "BOOKSITE Admin"
admin.site.site_title = "BOOKSITE Admin Portal"
admin.site.index_title = "Welcome to BOOKSITE Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mybooksite.urls")),
    path('accounts/', include("accounts.urls")),
    path('carts/', include("carts.urls")),
    # path('accounts/', include("django.contrib.auth.urls")),
] 

mybooksite/urls.py
from django.urls import path

from .views import BookDetailView, IndexView, AboutUsView, SearchView, CategoryView


app_name = "mybooksite"
urlpatterns = [
    
    path('', IndexView.as_view(), name="index"),
    path('search/', SearchView.as_view(), name='search'),
    path('book-detail/<int:pk>', BookDetailView.as_view(), name="detail"),
    path('category/<int:pk>', CategoryView.as_view(), name='category'),
    path('about-us/', AboutUsView.as_view(), name="about_us"),
    
]

carts/models.py
from django.db import models
from django.utils import tree
from mybooksite.models import Book
from django.contrib.auth.models import User


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def __str__(self):

        return self.user.username


class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"User: {self.user.username} & Order time: {self.created_at}"

        
        

carts/views.py
from re import template
from django.http import Http404
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .models import Cart
from mybooksite.models import Book
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from mybooksite.models import Book
from .models import Checkout
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin




def get_count_cart(request):

    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user)
        count = cart.books.count()
        return count

    return 0




def get_items_in_cart(cart):
    item_in_cart = []

    for item in cart.books.all():
        item_in_cart.append(item.id)

    return item_in_cart



class CheckboxCheck(LoginRequiredMixin, View):

    def get(self, request):
        return HttpResponseRedirect(reverse('carts:cart'))

    def post(self, request):
        template = 'carts/checkout.html'
        checks = request.POST.getlist('checks')
        books = Book.objects.filter(id__in=checks)
        count = get_count_cart(request)
        total = 0
        for book in books:
            total += book.price

        context = {
            'books':books,
            'count': count,
            "total": total
        }

        return render(request, template, context)


class CartView(LoginRequiredMixin, View):
    template = "carts/cart.html"

    def get(self, request):
        cart = Cart.objects.get(user=request.user)
        item_in_cart = get_items_in_cart(cart)
        count = cart.books.count()
        context = {
                "cart": cart,
                "count": count,
                "item_in_cart":item_in_cart
            }
    
        return render(request, self.template, context)
    


class AddToCart(View):
    template = 'carts/partials/add_to_cart_alert.html'
    template_exist = 'carts/partials/add_to_cart_book_exist.html'
    template_out_of_stock = 'carts/partials/add_to_cart_book_out_of_stock.html'
    template_error = 'carts/partials/add_to_cart_book_error.html'

    def post(self, request, pk):
        try:
            cart = Cart.objects.get(user=request.user.id)
            book = Book.objects.get(pk=pk)
            if book.is_in_stock == 'out of stock':
                return render(request, self.template_out_of_stock)
            if book in cart.books.all():
                return render(request, self.template_exist)
        except:
            return render(request, self.template_error)

        cart.books.add(book)
        count = cart.books.count()
        context = {
            'new_count':count
        }
        
        return render(request, self.template, context)



class CartItemDelete(View):
    template = 'carts/partials/partial_cart.html'

    def delete(self, request, pk):
        try:
            cart = Cart.objects.get(user=request.user.id)
            book = Book.objects.get(pk=pk)
            cart.books.remove(book)
            count = cart.books.count()
            item_in_cart = get_items_in_cart(cart)
            context = {
                'cart': cart,
                'new_count': count,
                'item_in_cart': item_in_cart
            }
            return render(request, self.template, context)
        except:
            raise Http404("Cart not found")
        
    def get(self, request, pk):

        return HttpResponseRedirect(reverse('carts:cart', args=(int(request.user.id),)))



class RecentOrder(View):
    template = 'carts/recent_order.html'

    def post(self, request):
        checkout = Checkout.objects.create(user=request.user)
        try:
            list_id = request.POST.getlist('books')
            books = Book.objects.filter(id__in=list_id)
            total = 0
            for book in books:
                checkout.books.add(book)
                total += book.price
            checkout.total = total
            checkout.save()
            list_of_books = checkout.books.all()
            count = get_count_cart(request)
        except:
            raise Http404("User not found")
        context = {
            'total':total,
            'list_of_books':list_of_books,
            'count': count,
            'recent_order': checkout
        }
        return render(request, self.template, context)

    def get(self, request):
        try:
            orders = Checkout.objects.filter(user=request.user)
            recent_order = orders.order_by('-created_at')[0]
            list_of_books = recent_order.books.all()
            total = recent_order.total
            count = get_count_cart(request)
        except:
            raise Http404("Recent Order not found")
        context = {
                'total':total,
                'list_of_books':list_of_books,
                'count': count,
                'recent_order':recent_order
            }
        return render(request, self.template, context)



class ListOfOrders(View):
    template = 'carts/orders.html'

    def get(self, request):
        try:
            user_orders = Checkout.objects.filter(user=request.user).order_by('-created_at')
            count = get_count_cart(request)
        except:
            raise Http404("Orders not exist")
        context = {
            'user_orders': user_orders,
            'count': count
            }
        return render(request, self.template, context)



class DetailOrder(View):
    template = 'carts/list_of_order.html'

    def get(self, request, pk):
        try:
            recent_order = Checkout.objects.get(pk=pk)
            list_of_books = recent_order.books.all()
            count = get_count_cart(request)
            total = recent_order.total
        except:
            raise Http404("Order not found")       
        context = {
            'total':total,
            'list_of_books':list_of_books,
            'count': count,
            'recent_order':recent_order
        }

        return render(request, self.template, context)



class DeleteOrder(View):
    template_partial = 'carts/partials/partial_order.html'

    def delete(self, request, pk):
        try:
            order = Checkout.objects.get(pk=pk)
            order.delete()
            user_orders = Checkout.objects.filter(user=request.user).order_by('-created_at') 
        except:
            raise Http404("Order not found")
        context = {
            'user_orders': user_orders,
        }

        return render(request, self.template_partial, context)

templates/carts/cart.html
{% extends 'base.html' %} 

{% block content %}

  <div class="max-w-[80%] container mt-5 text-gray-800">

    <h2 class="text-2xl">Cart</h2>

    <div id="cart-card" class="mt-10"
    
        x-data="{

              ischeck:false,

              myList:[],

              mySelectAll:[],

              checkboxLabel: 'Select all', 

              fullList:{{item_in_cart}},

              removeSelectAll() {

                this.mySelectAll = []

                this.ischeck = false 

                this.checkboxLabel='Select all'
                
              },

              selectAll() {

              if (this.ischeck===false){

                  this.myList=this.fullList

                  this.ischeck=true

                  this.checkboxLabel='Deselect all'

                  this.mySelectAll = [1] 

              }

              else {

                  this.myList=[]

                  this.ischeck=false

                  this.checkboxLabel = 'Select all'

              }}}"
    >

      <form action="{% url 'carts:checkout' %}" method="post">

        {% if cart.books.all %}

          <div class="flex items-center justify-between">

            <div class="flex items-center space-x-2">

              <input x-model="mySelectAll" 
                  class="text-purple-600 rounded focus:ring-purple-600 hover:ring-purple-600" 
                  type="checkbox"
                  value="1" 
                  x-on:click="selectAll()">

              <p x-text="checkboxLabel"></p>
              
            </div>
            {% if cart.books.all.count > 4 %}
            <div>

              <button type="submit" class="px-3 py-2 text-white bg-purple-600 rounded-md hover:bg-purple-700">
                  
                Check out
              
              </button>
              
            </div>
            {% endif %}

          </div>

        {% endif %}

      

        {% csrf_token %}

        {% for item in cart.books.all %}
        
          <div class="flex flex-col items-center py-5 my-5 space-y-5 text-gray-800 bg-white border border-gray-300 rounded-md shadow-lg sm:justify-between sm:pl-6 sm:flex-row"> 
            
          
            <div class="flex items-center flex-none -ml-8 space-x-2 sm:ml-0">
              
              <!--checkbox-->
              <input x-model="myList" 
                     class="text-purple-600 rounded focus:ring-purple-600 hover:ring-purple-600" 
                     type="checkbox" 
                     name="checks" 
                     value="{{item.pk}}"
                     x-on:click="removeSelectAll()"
              >
              
              <a href="{% url 'mybooksite:detail' item.id %}">
                  <!--img-->
                <img
                  class="border border-gray-300 rounded-sm w-36 h-44 hover:ring-2 hover:ring-purple-600"
                  src="{{item.img.url}}"
                />

              </a>

            </div>

            <!--title-->
            <div class="flex flex-col items-center justify-center space-y-3">

              <h3 class="block max-w-md text-center">

                Title: {{ item.title }}
              
              </h3>

              <p class="block">

                Price: ${{item.price}}

              </p>

            </div>

            <!--delete-->
            <div class="flex items-center mx-10">

              <button
                x-data
                class="px-3 py-2 text-white bg-red-600 rounded-md hover:bg-red-700"
                x-on:click.prevent.default="$dispatch('open-modal{{item.id}}')"
              >
                Delete

              </button>

            </div>

            <!--Delete Confirm Modal-->
            <div x-data="{
              open{{item.id}}:false,
              
            }"
                  x-on:open-modal{{item.id}}.window="open{{item.id}}=true, overFlow=true"
                  x-show="open{{item.id}}" 
                  class="fixed inset-0 flex items-center text-gray-800"                
            >
              <div class="fixed inset-0 bg-gray-300 opacity-50">
                <!--modal background gray-->
              </div>
              
              <!--modal cart-->
              <div x-show="open{{item.id}}"
                   x-on:click.outside="open{{item.id}}=false, overFlow=false"
                   x-transition:enter="transition ease-out duration-300"
                   x-transition:enter-start="opacity-0 -translate-y-6"
                   x-transition:enter-end="opacity-100 translate-y-0"
                   x-transition:leave="transition ease-in duration-300"
                   x-transition:leave-start="opacity-100 translate-y-0"
                   x-transition:leave-end="opacity-0 -translate-y-6" 
              class="z-30 flex flex-col items-center p-10 mx-auto space-y-3 bg-white rounded-md shadow-md md:p-20 "
              >
        
                <svg xmlns="http://www.w3.org/2000/svg"
                    class="w-12 h-12 text-red-600" 
                    fill="none" 
                    viewBox="0 0 24 24" 
                    stroke="currentColor">
                  <path stroke-linecap="round" 
                        stroke-linejoin="round" 
                        stroke-width="2" 
                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
        
                <p class="text-xl">Are you sure?</p>
        
                <p>You want to delete this item?</p>
                
                <div class="flex items-center justify-center space-x-2"> <span></span>
                  <button x-on:click.prevent.default="open{{item.id}}=false, overFlow=false" class="px-3 py-2 text-white bg-red-600 rounded-md hover:bg-red-700">Cancel</button>
                  <button class="px-3 py-2 text-white bg-purple-600 rounded-md hover:bg-purple-700"
                  x-on:click.prevent.default="open{{item.id}}=false, overFlow=false"
                  hx-delete="{% url 'carts:cart_item_delete' item.id %}"
                  hx-target="#cart-card"
                  hx-swap="outerHTML"           
                  >
                    Ok
                  </button>
                </div>
              </div>
        
            </div>

          </div>
          {% empty %}
          
          <div class="mb-5 text-xl">

            <p>Your cart is empty</p>

          </div>

        {% endfor %}

        <div class="flex items-center justify-between">

          <div x-show="xcount > 0">

            Quantity: <span x-text="xcount"></span>

          </div>

          {% if cart.books.all %}

            <div>

              <button type="submit" class="px-3 py-2 text-white bg-purple-600 rounded-md hover:bg-purple-700">
                
                Check out
              
              </button>
            
            </div>

          {% endif %}

        </div>

      </form>  

    </div>

    
    
    
  </div>

{% endblock content %}

templates/carts/checkout.html
{% extends 'base.html' %}
{% block content %}

  <div class="container max-w-[80%] mt-5">

    <h1 class="mb-2 text-2xl">
      
      Checkout
    
    </h1>

    <div class="flex p-2 space-x-2 text-gray-700 border border-purple-300 rounded-sm shadow-md">

      <div>

        <svg xmlns="http://www.w3.org/2000/svg" 
             class="w-10 h-10 text-purple-700" 
             fill="none" 
             viewBox="0 0 24 24" 
             stroke="currentColor">

          <path stroke-linecap="round" 
                stroke-linejoin="round" 
                stroke-width="2" 
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        
        </svg>
        
      </div>
      

      <div class="text-purple-900">

        <p>

          Make sure your personal information is updated before making an order
          
        </p>
  
        <p>
  
          go to your profile and update your information there
  
        </p>
        
      </div>

    </div>

    <div class="p-2 my-3 overflow-auto text-gray-700 border-2 border-purple-300 border-dashed rounded-sm shadow-md">
      <div>
        <p>Name: <span>{{request.user.first_name}} {{request.user.last_name}}</span></p>
      </div>
      <div>
        <p>Address: <span>{{request.user.profile.address}}</span></p>
      </div>
      <div>
        <p>Cellphone number: <span>{{request.user.profile.cellphone_number}}</span></p>
      </div>
      <div>
        <p>Email Address: <span>{{request.user.email}}</span></p>
      </div>
      
    </div>
    
    <form class="mt-10" action="{% url 'carts:recent_order' %}" method="post">  

      {% csrf_token %}

      {% if total > 0 %}

        <p class="mb-10 text-xl text-gray-800">
          
          Total: <span class="text-2xl text-purple-600">${{total}}</span> 

        </p>

      {% endif %}
    
      {% for book in books %}

        <input class="hidden" type="checkbox" name="books" checked="true" value="{{book.pk}}">
        
        <div class="flex items-center mb-2 space-x-2 shadow-sm">

          <div class="flex-none w-20 h-20 overflow-hidden border border-gray-500 rounded-md">
            
            <img class="object-cover w-full h-full"
                 src="{{book.img.url}}" 
                 alt="{{book.title}}">
        
          </div>
          
          <div>

            <p class="font-semibold text-gray-800">Title: <span class="font-normal text-gray-900 line-clamp-1">{{book.title}}</span></p>
            <p class="font-semibold text-gray-800">Price: <span class="font-normal text-gray-900">${{book.price}}</span></p>

          </div>
          

        </div>
      

        {% empty %}

        <p class="text-xl">

          Please select items in your cart to place an order

        </p>
        
      {% endfor %}
      
      {% if total > 0 %}

        <button x-data class="px-3 py-2 mt-5 font-medium text-white bg-purple-600 rounded-md shadow-sm hover:bg-purple-700"
        {% if request.user.first_name == '' or request.user.last_name == ''%}
        x-on:click.prevent.default = "$dispatch('modal-open-error')"
        {% endif %}
        type="submit"
        >

          Submit Order
          
        </button>

      {% endif %}
      
      

    </form>
    <!--Error modal-->
      <div id="alert" 
          class="container fixed inset-x-0 px-4 top-9" 
          x-data="{isAlert:false}" 
          x-cloak
          x-transition:enter="transition ease-out duration-300"
          x-transition:enter-start="opacity-0 scale-90"
          x-transition:enter-end="opacity-100 scale-100"
          x-transition:leave="transition ease-in duration-300"
          x-transition:leave-start="opacity-100  scale-100"
          x-transition:leave-end="opacity-0 scale-90" 
          x-show="isAlert"
          x-on:modal-open-error.window="isAlert=true, overFlow=true"        
      >
          
          
          <div x-on:click.away="isAlert=false, overFlow=false" class="z-50 flex w-full max-w-sm mx-auto overflow-hidden bg-white border border-red-500 rounded-lg shadow-xl">
              <div class="flex items-center justify-center w-12 bg-red-500">
                  <svg class="w-6 h-6 text-white fill-current" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                      <path d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z"/>
                  </svg>
              </div>
              
              <div class="px-4 py-2 -mx-3">
                  <div class="mx-3">
                      <span class="font-semibold text-red-500">Error</span>
                      <p class="text-sm text-gray-800">Please edit your profile first before ordering</p>
                  </div>
              </div>
          </div>
          
      </div>

  </div>

{% endblock %}

templates/carts/list_of_order.html
{% extends 'base.html' %}

{% block content %}

  <div class="container max-w-[80%] mt-5 text-gray-800">

    <h1 class="text-2xl">

        Order

    </h1>
    <h2 class="mt-2 font-semibold text-purple-600">

      Order Date: <span>{{recent_order.created_at}}</span>

    </h2>

    <div class="p-2 my-3 overflow-auto text-gray-700 border-2 border-purple-300 border-dashed rounded-sm shadow-md">
      
      <div>
        
        <p>Name: <span>{{request.user.first_name}} {{request.user.last_name}}</span></p>
      
      </div>
      
      <div>
        
        <p>Address: <span>{{request.user.profile.address}}</span></p>
      
      </div>
      
      <div>
        
        <p>Cellphone number: <span>{{request.user.profile.cellphone_number}}</span></p>
      
      </div>
      
      <div>
      
        <p>Email Address: <span>{{request.user.email}}</span></p>
      
      </div>
      
    </div>

    <p class="text-xl">Total: $<span class="text-purple-600 ">{{total}}</span></p>

    {% for book in list_of_books %}
      
      <div class="flex items-center my-2 space-x-2 shadow-md">
        
        <div class="flex-none w-20 h-20 overflow-hidden border border-gray-300 rounded-md">
          
          <img class="object-cover w-full h-full"
              src="{{book.img.url}}" 
              alt="{{book.title}}">
        
        </div>
        
        <p class="text-clip line-clamp-1">{{book.title}}</p>
      
      </div>
        
    {% endfor %}

    <p class="text-xl">Total: $<span class="text-purple-600 ">{{total}}</span></p>

  </div>
    
{% endblock %}

templates/carts/orders.html
{% extends 'base.html' %}

{% block content %}

  <div class="container max-w-[80%] mt-5 text-gray-800">

    <div class="my-3">
      <h2>
        List of Orders
      </h2>
    </div>

    <div id="order-card" class="p-2 border border-gray-300 rounded-md">
      {%for order in user_orders%}
        <div class="py-2 my-3 space-y-2 border-t border-b border-gray-300">
          <p>Date: {{order.created_at}}</p>
          <p>Quantity: {{order.books.all.count}}</p>
          <p>Total: ${{order.total}}</p>
          <a href="{% url 'carts:detail_order' order.id %}">
            <button class="px-3 py-2 text-xs text-white bg-purple-600 rounded-md shadow hover:bg-purple-700">
              See list
            </button>
          </a>
          <button class="px-3 py-2 text-xs text-white bg-red-600 rounded-md shadow hover:bg-red-700"
                  x-on:click="$dispatch('open-modal{{order.id}}')"
                  >
            Cancel Order
          </button>
        </div>

        <!--Delete Confirm Modal-->
        <div x-data="{
          open{{order.id}}:false,
          
        }"
              x-on:open-modal{{order.id}}.window="open{{order.id}}=true, overFlow=true"
              x-show="open{{order.id}}" 
              class="fixed inset-0 flex items-center text-gray-800"                
        >
          <div class="fixed inset-0 bg-gray-300 opacity-50">
            <!--modal background gray-->
          </div>
          
          <!--modal cart-->
          <div x-show="open{{order.id}}"
               x-on:click.outside="open{{order.id}}=false, overFlow=false"
               x-transition:enter="transition ease-out duration-300"
               x-transition:enter-start="opacity-0 -translate-y-6"
               x-transition:enter-end="opacity-100 translate-y-0"
               x-transition:leave="transition ease-in duration-300"
               x-transition:leave-start="opacity-100 translate-y-0"
               x-transition:leave-end="opacity-0 -translate-y-6" 
          class="z-30 flex flex-col items-center p-10 mx-auto space-y-3 bg-white rounded-md shadow-md md:p-20 "
          >
    
            <svg xmlns="http://www.w3.org/2000/svg"
                class="w-12 h-12 text-red-600" 
                fill="none" 
                viewBox="0 0 24 24" 
                stroke="currentColor">
              <path stroke-linecap="round" 
                    stroke-linejoin="round" 
                    stroke-width="2" 
                    d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
    
            <p class="text-xl">Are you sure?</p>
    
            <p>You want to delete this order?</p>
            
            <div class="flex items-center justify-center space-x-2"> <span></span>
              <button x-on:click.prevent.default="open{{order.id}}=false, overFlow=false" class="px-3 py-2 text-white bg-red-600 rounded-md hover:bg-red-700">Cancel</button>
              <button class="px-3 py-2 text-white bg-purple-600 rounded-md hover:bg-purple-700"
              x-on:click.prevent.default="open{{order.id}}=false, overFlow=false"
              hx-delete="{% url 'carts:delete_order' order.id %}"
              hx-target="#order-card"
              hx-swap="outerHTML"           
              >
                Ok
              </button>
            </div>
          </div>
    
        </div>

        {% empty %}

        <p class="text-xl">

          No recent orders

        </p>
        
      {%endfor%}
    </div>
    
      
  </div>

{% endblock %}

templates/carts/recent_order.html
{% extends 'base.html' %}

{% block content %}

  <div class="container max-w-[80%] mt-5 text-gray-800">

    <h1 class="text-2xl">

        Recent Order

    </h1>
    <h2 class="mt-2 font-semibold text-purple-600">

      Order Date: <span>{{recent_order.created_at}}</span>

    </h2>

    <div class="p-2 my-3 overflow-auto text-gray-700 border-2 border-purple-300 border-dashed rounded-sm shadow-md">
      
      <div>
        
        <p>Name: <span>{{request.user.first_name}} {{request.user.last_name}}</span></p>
      
      </div>
      
      <div>
        
        <p>Address: <span>{{request.user.profile.address}}</span></p>
      
      </div>
      
      <div>
        
        <p>Cellphone number: <span>{{request.user.profile.cellphone_number}}</span></p>
      
      </div>
      
      <div>
      
        <p>Email Address: <span>{{request.user.email}}</span></p>
      
      </div>
      
    </div>

    <p class="text-xl">Total: $<span class="text-purple-600 ">{{total}}</span></p>

    {% for book in list_of_books %}
      
      <div class="flex items-center my-2 space-x-2 shadow-md">
        
        <div class="flex-none w-20 h-20 overflow-hidden border border-gray-300 rounded-md">
          
          <img class="object-cover w-full h-full"
              src="{{book.img.url}}" 
              alt="{{book.title}}">
        
        </div>
        
        <p class="text-clip line-clamp-1">{{book.title}}</p>
      
      </div>
        
    {% endfor %}

    <p class="text-xl">Total: $<span class="text-purple-600 ">{{total}}</span></p>

  </div>
    
{% endblock %}