accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from accounts.views import (
    MyLoginView,
    MyLogoutView, 
    CheckUsername, 
    CheckEmail, 
    MyRegisterView,
    PasswordResetRequest,
    ProfileView,
    ProfileEdit,
    RegisterSuccess,
)


app_name = "accounts"
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', MyLoginView.as_view(), name="login"),
    path('logout/', MyLogoutView.as_view(), name="logout"),
    path('register-success/', RegisterSuccess.as_view(), name="register_success"),
    path('register/', MyRegisterView.as_view(), name='register'),
    path('password-change/', PasswordChangeView.as_view(template_name="accounts/password_change.html"), name='password_change'),
    path('password-change-done/', PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"), name='password_change_done'),
    path('password-reset/', PasswordResetRequest.as_view(), name='password_reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html",success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),name='password_reset_complete'),
]

htmx_urlpatterns = [
    path('check-username/', CheckUsername.as_view(), name="check_username"),
    path('check-email/', CheckEmail.as_view(), name='check_email'),
    path('edit-profile', ProfileEdit.as_view(), name='edit_profile'),
]

urlpatterns += htmx_urlpatterns

carts/urls.py
from django.urls import path
from carts.views import (
    CheckboxCheck,
    CartView,
    AddToCart,
    CartItemDelete,
    DeleteOrder,
    RecentOrder,
    ListOfOrders,
    DetailOrder,
)



app_name="carts"
urlpatterns = [

    path('', CartView.as_view(), name="cart"),
    path('add-to-cart/<int:pk>/', AddToCart.as_view(), name="add_to_cart"),
    path('checkout/', CheckboxCheck.as_view(), name="checkout"),
    path('recent-order/', RecentOrder.as_view(), name="recent_order"),
    path('orders/', ListOfOrders.as_view(), name='orders'),
    path('order-detail/<int:pk>/', DetailOrder.as_view(), name="detail_order")
]

htmx_urlpatterns = [
    path('cart-item-delete/<int:pk>/', CartItemDelete.as_view(), name="cart_item_delete"),
    path('delete-order/<int:pk>/', DeleteOrder.as_view(), name="delete_order")
]

urlpatterns += htmx_urlpatterns

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "BOOKSITE Admin"
admin.site.site_title = "BOOKSITE Admin Portal"
admin.site.index_title = "Welcome to BOOKSITE Portal"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mybooksite.urls")),
    path('accounts/', include("accounts.urls")),
    path('carts/', include("carts.urls")),
    # path('accounts/', include("django.contrib.auth.urls")),
] 

mybooksite/urls.py
from django.urls import path

from .views import BookDetailView, IndexView, AboutUsView, SearchView, CategoryView


app_name = "mybooksite"
urlpatterns = [
    
    path('', IndexView.as_view(), name="index"),
    path('search/', SearchView.as_view(), name='search'),
    path('book-detail/<int:pk>', BookDetailView.as_view(), name="detail"),
    path('category/<int:pk>', CategoryView.as_view(), name='category'),
    path('about-us/', AboutUsView.as_view(), name="about_us"),
    
]

templates/components/bottom_nav.html
<!--bottom-->

<div class="flex items-start justify-center gap-3 text-xs">
  {% if page_obj.has_previous %}

  <a
    class="px-2 py-1 text-center text-gray-600 border border-purple-600 rounded hover:bg-purple-700 hover:text-white"
    href="?page=1"
  >
    <span class="font-bold">&laquo;</span> <span class="hidden md:inline">First</span>
  </a>

  <a
    class="px-2 py-1 text-center text-gray-600 border border-purple-600 rounded hover:bg-purple-700 hover:text-white"
    href="?page={{ page_obj.previous_page_number }}"
  >
  <span class="font-bold">&lsaquo;</span> <span class="hidden md:inline">Previous</span>
  </a>

  {% endif %}
   
  {% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}

  <a
    class="px-2 py-1 text-center text-white bg-purple-600 border border-purple-600 rounded hover:bg-purple-700 hover:text-white"
    href="?page={{ num }}"
  >
    {{ num }}
  </a>

  {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}

  <a
    class="px-2 py-1 text-center text-gray-600 border border-purple-600 rounded hover:bg-purple-700 hover:text-white"
    href="?page={{ num }}"
  >
    {{ num }}
  </a>

  {% endif %}
  {% endfor %} 
  {% if page_obj.has_next %}

  <a
    class="px-2 py-1 text-center text-gray-600 border border-purple-600 rounded hover:bg-purple-700 hover:text-white"
    href="?page={{ page_obj.next_page_number }}"
  >
  <span class="hidden md:inline">Next</span> <span class="font-bold">&rsaquo;</span>
  
  </a>

  <a
    class="px-2 py-1 text-center text-gray-600 border border-purple-600 rounded hover:bg-purple-700 hover:text-white"
    href="?page={{ page_obj.paginator.num_pages }}"
  >
  <span class="hidden md:inline">Last</span> <span class="font-bold">&raquo;</span>
  </a>

  {% endif %}
  
</div>

templates/components/card.html
{% load static %}

<!--card-->
<div class="flex flex-col justify-between min-h-full px-2 py-2 space-y-3 text-gray-800">

  <a href="{% url 'mybooksite:detail' book.pk %}">

    <!--img-->
    <div class="flex items-center justify-center">

      <div
        class="overflow-hidden rounded-lg shadow outline outline-1 outline-gray-400 hover:outline-purple-600 hover:outline-2"
      >

        <img
          class="w-36 h-44"
          src="{{ book.img.url }}"
          alt="{{ book.title }}"
        />

      </div>

    </div>

  </a>

  <!--rating-->
  <div class="flex justify-center"
    x-data="{

      ischeck:true,

      ar:[],

      stars:[1,2,3,4,5],

      hoverOver(star) {

          for (let i = 0; i < star; i++) {

              this.ar.push(i+1)

          }
      },

    }">

    <template x-for="star in stars">
      
      <p class="cursor-pointer" x-model="ar" x-bind:value="star" x-on:mouseover="hoverOver(star)" x-on:mouseleave="ar=[]">
        
        <svg

          x-bind:class="{

            'text-yellow-400': {{book.rating}}>=star,

            'text-yellow-500': ar.includes(star),

          }"
          class="w-6 h-6"

          xmlns="http://www.w3.org/2000/svg"

          viewBox="0 0 20 20"

          fill="currentColor"

        >
          <path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
          />

        </svg>
        
      </p>
        
      
    </template>

  </div>

  <!--title-->
  <div class="text-base font-semibold text-center line-clamp-1">

    <p class="">

      {{ book.title }}

    </p>

  </div>

  <!--subtitle-->
  <div class="flex items-center justify-center text-xs font-normal text-center line-clamp-3">

    {{ book.description|truncatewords:30 }}

  </div>

  <!--price-->
  <div class="font-semibold text-center">

    $ {{book.price}}

  </div>

  <!--in_stock-->
  <div class="flex items-center justify-center 
             {% if book.is_in_stock == 'in stock' %} 
             text-green-600 
             {% else %}
             text-red-500
             {% endif %}"
              
  >

    <div>

      {% if book.is_in_stock == 'in stock' %}
      
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="w-4 h-4"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >

        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M5 13l4 4L19 7"
        />

      </svg>
      {% else %}

      <svg xmlns="http://www.w3.org/2000/svg" 
           class="w-4 h-4" 
           viewBox="0 0 20 20" 
           fill="currentColor"
      >
        <path 
          fill-rule="evenodd" 
          d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" 
          clip-rule="evenodd" 
        />

      </svg>
      
      {%endif%}

    </div>

    <div>

      {{ book.is_in_stock }}

    </div>

  </div>

  <!--addtocart btn-->
  <div class="flex items-center justify-center">

    <button

      hx-post="{% url 'carts:add_to_cart' book.pk %}"

      hx-trigger="click"

      hx-swap="outerHtml settle:300ms"

      hx-target="#alert"

      class="w-full px-4 py-2 mt-2 text-xs font-semibold text-center text-white bg-purple-600 rounded-full shadow-md hover:bg-purple-700"
    >

      add to cart

    </button>

  </div>

</div>

templates/components/footer.html
<!--footer-->
<div class="py-10 text-xl font-bold text-white bg-purple-600">

  <div class="flex items-center justify-center hover:text-gray-300">

      <a href="{% url 'mybooksite:index' %}">

          Mybooksite

      </a>

  </div>
  
</div>

templates/components/hero.html
<div class="flex flex-col ml-3 text-gray-800 sm:ml-0">

  <h2 class="text-xl font-semibold sm:text-2xl md:text-3xl lg:text-5xl">

    Never stop learning

  </h2>

  <h2 class="text-xl font-semibold sm:text-2xl md:text-3xl lg:text-5xl lg:mt-4">

    Order your books

  </h2>

  {% if not user.is_authenticated %}

    <div class="mt-2">

      <a href="{% url 'accounts:register' %}">

        <button
          href="{% url 'accounts:register' %}"
          id="joinBtn"
          class="flex items-center justify-center p-2 text-lg font-medium text-white bg-purple-600 rounded-sm shadow-md hover:bg-purple-700 lg:text-2xl lg:mt-4"
        >

          Join now

        </button>

      </a>

    </div>

  {% endif %}

</div>

templates/components/nav_categories.html
<!--sub nav-->
<div x-data="{ isOpen: false }" class="relative flex items-center gap-3">

  <div x-on:click="isOpen = !isOpen, overFlow = !overFlow"
  
       class="flex cursor-pointer"
  >
    <div class="flex items-center text-sm font-medium text-gray-800">

      Categories

    </div>

    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="w-5 h-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M19 9l-7 7-7-7"
      />
    </svg>

  </div>

  <div
    x-on:click="isOpen = !isOpen, overFlow=!overFlow"

    x-show="isOpen" x-cloak

    class="fixed inset-0 z-10 w-full h-full bg-gray-500 opacity-50 cursor-default"

  >
  </div>

  <div x-show="isOpen" x-cloak

  x-transition:enter="transition ease-out duration-300"
  x-transition:enter-start="opacity-0 -translate-y-6"
  x-transition:enter-end="opacity-100 translate-0"
  x-transition:leave="transition ease-in duration-300"
  x-transition:leave-start="opacity-100 translate-0"
  x-transition:leave-end="opacity-0 -translate-y-6"
  
       class="absolute z-20 w-48 h-64 overflow-y-auto font-medium rounded shadow-md text-grey-800 bg-slate-100 top-6"
  >

    <ul class="flex flex-col items-center justify-center w-full">

      {% for category in categories %}

        <a class="w-full" href="{% url 'mybooksite:category' category.pk %}">
          
          <li class="flex justify-center py-2 hover:bg-purple-600 hover:text-white">

            {{ category }}

          </li>

        </a>  
      {% endfor %}

    </ul>

  </div>
  
</div>

templates/components/navbar.html
<!--navbar-->
<div class="py-2 bg-purple-600 md:justify-between" x-data="{isOpen: false}">

  <div class="container max-w-[80%] flex justify-center items-center md:justify-between md:items-center">

    <div class="text-xl font-bold text-white hover:text-gray-300 text">

      <a href="{% url 'mybooksite:index' %}">Mybooksite</a>
      
    </div>

    <!--navigation-->
    <div class="relative items-center justify-center hidden gap-3 md:flex lg:gap-4">

      <div class="font-medium text-white hover:text-gray-300">

        <a href="{% url 'mybooksite:about_us'%}"> About us </a>
        
      </div>

      <!--cart icon-->
      {% if user.is_authenticated %}

        <a href="{% url 'carts:cart' %}">

          <div class="flex">

            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="w-6 h-6 text-white hover:text-gray-300"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
              />
            </svg>

            <p id="item-count" 
               x-text="xcount" 
               class="flex items-center justify-center w-6 h-6 text-xs font-semibold text-white rounded-full bg-violet-800">
            </p>   

          </div>
          
        </a>
        
      {% endif %}

      
      {% if not user.is_authenticated %}

      <div class="font-medium text-white">

        <a class="hover:text-gray-300" href="{% url 'accounts:login' %}">Sign-in</a> | 

        <a class="hover:text-gray-300" href="{% url 'accounts:register' %}">Sign-up</a>

      </div>

      {% endif %}

      {% if user.is_authenticated %}

        <div x-on:click="isOpen=!isOpen, overFlow=!overFlow">

          {% include 'components/user_nav_button.html'%}

        </div>
        <div class="absolute right-0 z-50 top-10">

          {% include 'components/user_nav.html' %}
          
        </div>
        
      {% endif %}
    </div>
      
    <!--hamburger button-->
    <div
      x-data
      class="absolute top-1 right-3 md:hidden"
    >

      {% if not user.is_authenticated %}

        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="w-6 h-6 mt-2 text-white cursor-pointer"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          x-on:click="$dispatch('open-side-dropdown'), overFlow=!overFlow, isOpen=!isOpen"
          
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M4 6h16M4 12h16M4 18h16"
          />
        </svg>

      {% else %}

        <div class="flex items-center space-x-2" x-on:click="isOpen=!isOpen, overFlow=!overFlow">

          {% include 'components/user_nav_button.html' %}

        </div>

        <div class="absolute right-0 z-50 top-10">

          {% include 'components/user_nav.html' %}

        </div>
        
      {% endif %}

        <!--sidebar--> <!--mobile-nav-->
      {% if not user.is_authenticated %}
        <div x-data="{open:false}"
             x-on:open-side-dropdown.window="open=true"
        >
          <div x-show="open"
               x-on:click="open=false, overFlow=false" 
               class="fixed inset-0 bg-gray-300 opacity-50"
          >
          <!--bg button to close the dropdown-->
          </div>
          <div x-show="open" 
              x-transition:enter="transition ease-out duration-300"
              x-transition:enter-start="opacity-0 -translate-y-6"
              x-transition:enter-end="opacity-100 translate-y-0"
              x-transition:leave="transition ease-in duration-300"
              x-transition:leave-start="opacity-100  translate-y-0"
              x-transition:leave-end="opacity-0 -translate-y-6" 
                class="absolute right-0 z-50 overflow-hidden text-gray-800 bg-white rounded shadow-md w-36 top-9">
            <ul
              class="flex flex-col items-center justify-center font-medium text-center text-gray-800"
            >

                <a class="w-full"href="{% url 'accounts:login'%}">

                  <li class="py-2 cursor-pointer hover:bg-purple-600 hover:text-white">

                    Login

                  </li>

                </a>

                <a class="w-full" href="{% url 'accounts:register' %}">

                  <li class="w-full py-2 cursor-pointer hover:bg-purple-600 hover:text-white">

                      Register

                  </li>

                </a>
                
                <a class="w-full" href="{% url 'mybooksite:about_us' %}">

                  <li class="py-2 cursor-pointer hover:bg-purple-600 hover:text-white">

                    About Us

                  </li>

                </a>

            </ul>

          </div>

        </div>
        
      {% endif %}
      
    </div>
    
  </div>
  
</div>




<!--Search bar-->
{% include 'components/search.html' %}

templates/components/search.html
<form class="mt-3" action="{% url 'mybooksite:search' %}">
    <div class="relative flex max-w-[80%] mx-auto md:max-w-[60%]">
      
        <input name="q" class="flex items-center w-full py-1 pl-8 text-sm rounded-lg focus:ring-0 focus:border-purple-600 hover:ring-1 hover:ring-purple-600" type="text" placeholder="Search">
      
        <div class="absolute pl-1 text-gray-500 -sm top-1 left-1">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
        </div>

        <button type="submit" class="hidden">
           
        </button>
    
    </div>
   
    
      
</form>

templates/components/search_results.html
{% extends 'base.html' %}

{% block content %}

  <div class="container sm:max-w-[80%] mt-5">

    <div id="alert" class="fixed inset-x-0 z-20 top-9"></div>

    <h2 class="mx-2 text-2xl sm:mx-0">

      Search results: "{{q}}"

    </h2>

    <section class="mt-8 mx-2 
                    sm:mx-0 
                    grid grid-cols-2 gap-2 
                    sm:grid-cols-3 
                    md:grid-cols-4 
                    lg:grid-cols-5 min-h-[60vh]"
    >

      {% for book in books %}

        <div class="mb-12 border border-gray-300 rounded-md shadow-md">

          {% include 'components/card.html'%}

        </div>

      {% endfor %}

    </section>
    
  </div>

{% endblock %}

templates/components/user_nav.html
<!--hidden button to close the dropdown-->
<button x-show="isOpen"
class="fixed inset-0 w-full h-full bg-gray-500 opacity-50 cursor-default -z-30"
x-on:click="overFlow=!overFlow, isOpen=false"
>
</button>

<!--usernav dropown-->
<div x-show="isOpen"
    x-transition:enter="transition ease-out duration-300"
    x-transition:enter-start="-translate-y-6"
    x-transition:enter-end="translate-0"
    x-transition:leave="transition ease-in duration-300"
    x-transition:leave-start="translate-0 opacity-100"
    x-transition:leave-end="-translate-y-6 opacity-0"
    x-cloak 
     class="overflow-hidden font-medium text-gray-800 bg-white rounded w-36">


  <!--navigation-->
  <ul class="flex flex-col items-center gap-2 bg-white cursor-pointer">

    <a class="w-full"href="{% url 'accounts:profile' %}">

      <li class="py-2 text-center hover:bg-purple-600 hover:text-white">My Profile</li>
      
    </a>

    <a class="w-full md:hidden"href="{% url 'mybooksite:about_us' %}">

      <li class="py-2 text-center hover:bg-purple-600 hover:text-white">About us</li>
      
    </a>


    <a class="w-full" href="{% url 'carts:cart' %}">

      <li class="flex justify-center py-2 text-center hover:bg-purple-600 hover:text-white">

        Cart

        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="w-6 h-6"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
          />
        </svg>

        <span class="flex items-center justify-center w-4 h-4 text-xs font-semibold text-white bg-purple-600 rounded-full" x-text="xcount"></span> 

      </li>
      
    </a>

    <a class="w-full" href="{% url 'carts:orders' %}">

      <li class="w-full py-2 text-center hover:bg-purple-600 hover:text-white">

        See Orders
        
      </li>


    </a>

      <li x-on:click="$dispatch('open-modal')" class="w-full py-2 text-center hover:bg-purple-600 hover:text-white">

        Logout

      </li>

  </ul>
   <!--logout Confirm Modal-->
   <div x-data="{
    open:false,
    
  }"
        x-on:open-modal.window="open=true, overFlow=true"
        x-show="open" 
        class="fixed inset-0 flex items-center text-gray-800"                
  >
    <div class="fixed inset-0 bg-gray-300 opacity-50">
      <!--modal background gray-->
    </div>
    
    <!--modal cart-->
    <div x-show="open"
         x-on:click.outside="open=false, overFlow=false"
         x-transition:enter="transition ease-out duration-300"
         x-transition:enter-start="opacity-0 -translate-y-6"
         x-transition:enter-end="opacity-100 translate-y-0"
         x-transition:leave="transition ease-in duration-300"
         x-transition:leave-start="opacity-100 translate-y-0"
         x-transition:leave-end="opacity-0 -translate-y-6" 
    class="z-30 flex flex-col items-center p-10 mx-auto space-y-3 bg-white rounded-md shadow-md md:p-20 "
    >

      <svg xmlns="http://www.w3.org/2000/svg"
          class="w-12 h-12 text-red-600" 
          fill="none" 
          viewBox="0 0 24 24" 
          stroke="currentColor">
        <path stroke-linecap="round" 
              stroke-linejoin="round" 
              stroke-width="2" 
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
      </svg>

      <p class="text-xl">Are you sure?</p>

      <p>You want to logout? </p>
      
      <div class="flex items-center justify-center space-x-2"> <span></span>
        <button x-on:click.prevent.default="open=false, overFlow=false" class="px-3 py-2 text-white bg-red-600 rounded-md hover:bg-red-700">Cancel</button>
        <a class="px-3 py-2 text-white bg-purple-600 rounded-md hover:bg-purple-700"
        x-on:click="open=false, overFlow=false"
        href="{% url 'accounts:logout' %}"          
        >
          Ok
      </a>
      </div>
    </div>

  </div>
  
</div>

templates/components/user_nav_button.html
<div class="w-8 h-8 overflow-hidden rounded-full cursor-pointer ">

  <img class="object-cover w-full h-full" 
       src="{% if request.user.profile.avatar.url is not null %}
            {{request.user.profile.avatar.url}}
            {% else %}
            https://res.cloudinary.com/derqjgcyg/image/upload/v1645411542/media/avatar/default_rvyiey.jpg
            {% endif %}
            "
             
       alt="avatar"
  >

</div>